from enum import Enum


class BuildStatus(str, Enum):
    PENDING = "PENDING"
    VISIONARY_REFINING = "VISIONARY_REFINING"
    BLUEPRINT_DESIGNING = "BLUEPRINT_DESIGNING"
    CRAFTSMAN_IMPLEMENTING = "CRAFTSMAN_IMPLEMENTING"
    GUARDIAN_VALIDATING = "GUARDIAN_VALIDATING"
    SHIPMASTER_DEPLOYING = "SHIPMASTER_DEPLOYING"
    REFINING_PROMPT = "REFINING_PROMPT"
    GENERATING_CODE = "GENERATING_CODE"
    TESTING = "TESTING"
    FIXING_ERRORS = "FIXING_ERRORS"
    BUILDING_IMAGE = "BUILDING_IMAGE"
    DEPLOYING = "DEPLOYING"
    VERIFYING_APIS = "VERIFYING_APIS"
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class ToolStatus(str, Enum):
    DEPLOYING = "DEPLOYING"
    RUNNING = "RUNNING"
    FAILED = "FAILED"
    STOPPED = "STOPPED"
